/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Vehiculo;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author braya
 */
public class CrearVehiculo extends javax.swing.JInternalFrame {
    private ControladorCliente controladorCliente;
    private VentanaCrearCliente ventanaCrearCliente;
    private ControladorVehiculo controladorVehiculo;
    private VentanaPrincipal ventanaPrincipal; 
    
    private String crearC;
    private String exito;
    private String incom;
    /**
     * Creates new form CrearVehiculo
     */
    public CrearVehiculo(ControladorCliente controladorCliente,VentanaCrearCliente ventanaCrearCliente,ControladorVehiculo controladorVehiculo,VentanaPrincipal ventanaPrincipal ) {
        initComponents();
        this.controladorCliente= controladorCliente;
        this.ventanaCrearCliente=ventanaCrearCliente;
        this.ventanaPrincipal=ventanaPrincipal;
        this.controladorVehiculo=controladorVehiculo;
    }

    public void setCrearC(String crearC) {
        this.crearC = crearC;
    }

    public void setExito(String exito) {
        this.exito = exito;
    }

    public void setIncom(String incom) {
        this.incom = incom;
    }
    
    
    public JButton getBtnBuscarCliente() {
        return btnBuscarCliente;
    }

    public JButton getBtnRegistrarVehiculo() {
        return btnRegistrarVehiculo;
    }

    public JLabel getjCedula() {
        return jCedula;
    }

    public JLabel getjDireccion() {
        return jDireccion;
    }

    public JLabel getjInfo() {
        return jInfo;
    }

    public JLabel getjMarca() {
        return jMarca;
    }

    public JLabel getjModelo() {
        return jModelo;
    }

    public JLabel getjNombre() {
        return jNombre;
    }

    public JLabel getjPlaca() {
        return jPlaca;
    }

    public JLabel getjTelefono() {
        return jTelefono;
    }
    
    
//    public JTextField getTxtPlaca() {
//        return txtPlaca;
//    }
//
//    public JTextField getTxtMarca() {
//        return txtMarca;
//    }
//
//    public JTextField getTxtModelo() {
//        return txtModelo;
//    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPlaca = new javax.swing.JLabel();
        jMarca = new javax.swing.JLabel();
        btnRegistrarVehiculo = new javax.swing.JButton();
        jModelo = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        jCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jTelefono = new javax.swing.JLabel();
        txtNumeroFormateado = new javax.swing.JFormattedTextField();
        jInfo = new javax.swing.JLabel();
        btnBuscarCliente = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPlaca.setText("Ingrese Placa:");

        jMarca.setText("Ingrese marca:");

        btnRegistrarVehiculo.setForeground(new java.awt.Color(0, 153, 153));
        btnRegistrarVehiculo.setText("Registrar Vehiculo");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });

        jModelo.setText("Ingrese modelo:");

        jCedula.setText("Ingese Cedula del Cliente");

        jNombre.setText("Nombre del Cliente:");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));

        jDireccion.setText("Direccion:");

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(255, 255, 204));

        jTelefono.setText("Telefono:");

        txtNumeroFormateado.setEditable(false);
        txtNumeroFormateado.setBackground(new java.awt.Color(255, 255, 204));

        jInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jInfo.setText("Datos del Cliente Dueño del Vehiculo");

        btnBuscarCliente.setForeground(new java.awt.Color(0, 153, 153));
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPlaca)
                                    .addComponent(jMarca)
                                    .addComponent(jModelo))
                                .addGap(100, 100, 100)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBuscarCliente)
                                .addComponent(jCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNumeroFormateado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrarVehiculo)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMarca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefono)
                    .addComponent(txtNumeroFormateado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVehiculo)
                    .addComponent(btnBuscarCliente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String cedula= txtCedula.getText();
        Cliente u=controladorCliente.buscrarClientePorCedula(cedula);
        if(u!= null)
        {
            txtNombre.setText(u.getNombre());
            txtDireccion.setText(u.getDireccion());
            txtNumeroFormateado.setText(u.getTelefono());
            btnRegistrarVehiculo.setEnabled(true);        
            
        }else
        {
            int opcion=JOptionPane.showConfirmDialog(this, crearC); 
            btnRegistrarVehiculo.setEnabled(false);
            if(opcion== JOptionPane.YES_OPTION)
            {
                ventanaPrincipal.getDesktopPane().add(ventanaCrearCliente);
                ventanaCrearCliente.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed
 
     public void limpiar() {
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtCedula.setText("");
        txtNombre.setText("");
        txtNumeroFormateado.setText("");
        txtDireccion.setText("");
        
    }
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        btnRegistrarVehiculo.setEnabled(false);
//        localizacion = new Locale("es", "EC");
//        mensajes = ResourceBundle.getBundle("ec.edu.ups.idiomas.mensajes", localizacion);
        ventanaPrincipal.cambiarIdioma();
    }//GEN-LAST:event_formInternalFrameActivated
    
    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        if(!txtPlaca.getText().equals("")&&!txtMarca.getText().equals("")&&!txtModelo.getText().equals(""))
        {
            Vehiculo vehiculo =controladorVehiculo.crearVehiculo(txtPlaca.getText(), txtMarca.getText(), txtModelo.getText());
            String cedula = txtCedula.getText();
            controladorCliente.agregarVehiculo(vehiculo, cedula);
            JOptionPane.showMessageDialog(this, exito);
            limpiar();
            this.dispose();
        }else{JOptionPane.showMessageDialog(this, incom);}
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JLabel jCedula;
    private javax.swing.JLabel jDireccion;
    private javax.swing.JLabel jInfo;
    private javax.swing.JLabel jMarca;
    private javax.swing.JLabel jModelo;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jPlaca;
    private javax.swing.JLabel jTelefono;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JFormattedTextField txtNumeroFormateado;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
