/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorTiket;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Ticket;
import ec.edu.ups.modelo.Vehiculo;
//import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
//import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.JOptionPane;

/**
 *
 * @author braya
 */
public class VentanaSalidaVehiculo extends javax.swing.JInternalFrame {

    private Calendar fechaYHora;
    private ControladorCliente controladorCliente;
    private ControladorTiket controladorTicket;
    private ControladorVehiculo controladorVehiculo;

    private VentanaIngresarVehiculo ventanaIngresarVehiculo;
    private VentanaPrincipal ventanaPricipal;
    private Date FechaS;
    LocalDateTime local;

    private String noExiste;
    private String valido;
    private String pagar;
    private String si;
    private String no;
    private String cancelar;

    //private Object option;
    /**
     * Creates new form VentanaSalidaVehiculo
     */
    public VentanaSalidaVehiculo(ControladorCliente controladorCliente, ControladorTiket controladorTicket, ControladorVehiculo controladorVehiculo, VentanaPrincipal ventanaPrincipal, VentanaIngresarVehiculo ventanaIngresarVehiculo) {
        initComponents();
        this.controladorCliente = controladorCliente;
        this.controladorTicket = controladorTicket;
        this.controladorVehiculo = controladorVehiculo;
        this.ventanaIngresarVehiculo = ventanaIngresarVehiculo;
        this.ventanaPricipal = ventanaPrincipal;
        local = LocalDateTime.now();

        //option = new Object();
    }

    //metodo para calcular la fecha y hora automaticamente 
    public void FechaYHora() {
        LocalDateTime local = LocalDateTime.now();
        FechaS = java.sql.Timestamp.valueOf(local);
        txtFechaS.setText(local.toString());
    }

    public void setNoExiste(String noExiste) {
        this.noExiste = noExiste;
    }

    public void setValido(String valido) {
        this.valido = valido;
    }

    public void setPagar(String pagar) {
        this.pagar = pagar;
    }

    public JButton getBtnGenerarTicket() {
        return btnGenerarTicket;
    }

    public JButton getBtnInformacionTicket() {
        return btnInformacionTicket;
    }

    public JLabel getjCedula() {
        return jCedula;
    }

    public JLabel getjDireccion() {
        return jDireccion;
    }

    public JLabel getjFecha() {
        return jFecha;
    }

    public JLabel getjFechaS() {
        return jFechaS;
    }

    public JLabel getjTelefono() {
        return jTelefono;
    }

    public JLabel getjMarca() {
        return jMarca;
    }

    public JLabel getjModelo() {
        return jModelo;
    }

    public JLabel getjNombre() {
        return jNombre;
    }

    public JLabel getjNumeroT() {
        return jNumeroT;
    }

    public JLabel getjPlacaV() {
        return jPlacaV;
    }

    public JLabel getjTotal() {
        return jTotal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jNumeroT = new javax.swing.JLabel();
        jFechaS = new javax.swing.JLabel();
        jFecha = new javax.swing.JLabel();
        jCedula = new javax.swing.JLabel();
        jNombre = new javax.swing.JLabel();
        jDireccion = new javax.swing.JLabel();
        jTelefono = new javax.swing.JLabel();
        jPlacaV = new javax.swing.JLabel();
        jMarca = new javax.swing.JLabel();
        jModelo = new javax.swing.JLabel();
        jTotal = new javax.swing.JLabel();
        txtFechaE = new javax.swing.JTextField();
        txtNUmeroTicket = new javax.swing.JTextField();
        txtFechaS = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnGenerarTicket = new javax.swing.JButton();
        btnInformacionTicket = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jNumeroT.setText("Ingrese numero de ticket");

        jFechaS.setText("Fecha de salida");

        jFecha.setText("Fecha de entrada");

        jCedula.setText("Cedula del cliente");

        jNombre.setText("Nombre del cliente");

        jDireccion.setText("Direccion");

        jTelefono.setText("Telefono");

        jPlacaV.setText("Placa vehiculo");

        jMarca.setText("Marca");

        jModelo.setText("Modelo");

        jTotal.setText("Total a pagar");

        txtFechaE.setEditable(false);
        txtFechaE.setBackground(new java.awt.Color(255, 255, 204));

        txtFechaS.setEditable(false);
        txtFechaS.setBackground(new java.awt.Color(255, 255, 204));

        txtCedula.setEditable(false);
        txtCedula.setBackground(new java.awt.Color(255, 255, 204));

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(255, 255, 204));

        txtDireccion.setEditable(false);
        txtDireccion.setBackground(new java.awt.Color(255, 255, 204));

        txtTelefono.setEditable(false);
        txtTelefono.setBackground(new java.awt.Color(255, 255, 204));

        txtPlaca.setEditable(false);
        txtPlaca.setBackground(new java.awt.Color(255, 255, 204));

        txtMarca.setEditable(false);
        txtMarca.setBackground(new java.awt.Color(255, 255, 204));

        txtModelo.setEditable(false);
        txtModelo.setBackground(new java.awt.Color(255, 255, 204));

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 255, 204));

        btnGenerarTicket.setText("Generar ticket de salida");
        btnGenerarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTicketActionPerformed(evt);
            }
        });

        btnInformacionTicket.setText("Informacion Ticket");
        btnInformacionTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformacionTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jFecha)
                        .addComponent(jTotal)
                        .addComponent(jModelo)
                        .addComponent(jMarca)
                        .addComponent(jPlacaV)
                        .addComponent(jTelefono)
                        .addComponent(jDireccion)
                        .addComponent(jCedula)
                        .addComponent(jFechaS)
                        .addComponent(jNumeroT)
                        .addComponent(jNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInformacionTicket)
                        .addGap(31, 31, 31)))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNUmeroTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(txtFechaE)
                        .addComponent(txtFechaS)
                        .addComponent(txtCedula)
                        .addComponent(txtNombre)
                        .addComponent(txtDireccion)
                        .addComponent(txtTelefono)
                        .addComponent(txtPlaca)
                        .addComponent(txtMarca)
                        .addComponent(txtModelo)
                        .addComponent(txtTotal))
                    .addComponent(btnGenerarTicket))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNumeroT)
                    .addComponent(txtNUmeroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFecha)
                    .addComponent(txtFechaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFechaS)
                    .addComponent(txtFechaS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPlacaV)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInformacionTicket)
                    .addComponent(btnGenerarTicket))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformacionTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformacionTicketActionPerformed
        // TODO add your handling code here:
        if (txtNUmeroTicket.getText() != "") {
            FechaYHora();
            Ticket tiket = controladorTicket.buscarTiket(Integer.valueOf(txtNUmeroTicket.getText()));
            if (tiket == null) {
                int opcion = JOptionPane.showConfirmDialog(this, noExiste);
                if (opcion == JOptionPane.YES_OPTION) {
                    ventanaPricipal.getDesktopPane().add(ventanaIngresarVehiculo);
                    ventanaIngresarVehiculo.setVisible(true);
                    this.dispose();
                } else if (opcion == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(this, valido);
                    txtNUmeroTicket.setText("");
                }

            } else {
                LocalDateTime FechaEntrada = tiket.getFechaYHoraDeIngreso();
                //LocalDateTime localE = FechaEntrada.toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
                Vehiculo vehiculo = tiket.getVehiculo();
                txtFechaE.setText(FechaEntrada.toString());
                txtPlaca.setText(vehiculo.getPlaca());
                txtMarca.setText(vehiculo.getMarca());
                txtModelo.setText(vehiculo.getModelo());
                Cliente cliente = controladorCliente.buscarPorVehiculo(vehiculo.getPlaca());
                //Cliente cliente=vehiculo.getCliente();
                txtCedula.setText(cliente.getCedula());
                txtNombre.setText(cliente.getNombre());
                txtDireccion.setText(cliente.getDireccion());
                txtTelefono.setText(cliente.getTelefono());
//           DateTimeFormatter formato = DateTimeFormatter.ofPattern("yyyy-mm-dd HH:mm");
                LocalDate d1 = LocalDate.parse(FechaEntrada.toString(), DateTimeFormatter.ISO_LOCAL_DATE_TIME);
                LocalDate d2 = LocalDate.parse(local.toString(), DateTimeFormatter.ISO_LOCAL_DATE_TIME);
                Duration diff = Duration.between(d1.atStartOfDay(), d2.atStartOfDay());
                long diffDays = diff.toMillis();
                //txtTotal.setText(String.valueOf(diffDays));
                if (diffDays <= 10) {
                    txtTotal.setText(String.valueOf(0.25));
                } else if (diffDays > 10) {
                    int calcularTotal = (int) diffDays / 10;
                    calcularTotal = (int) (calcularTotal * 0.25);
                    txtTotal.setText(String.valueOf(calcularTotal));
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Ingrese un numero de ticket");
        }

    }//GEN-LAST:event_btnInformacionTicketActionPerformed

    private void btnGenerarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTicketActionPerformed

        Ticket tiket = controladorTicket.buscarTiket(Integer.valueOf(txtNUmeroTicket.getText()));
        if (tiket == null) {
            JOptionPane.showMessageDialog(this, "Primero verifique si existe si ticket");
        } else {
            controladorTicket.actualizar(Integer.valueOf(txtNUmeroTicket.getText()), Double.parseDouble(txtTotal.getText()), local);
            JOptionPane.showMessageDialog(this, pagar + txtTotal.getText());
            this.dispose();
        }
    }//GEN-LAST:event_btnGenerarTicketActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        ventanaPricipal.cambiarIdioma();
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarTicket;
    private javax.swing.JButton btnInformacionTicket;
    private javax.swing.JLabel jCedula;
    private javax.swing.JLabel jDireccion;
    private javax.swing.JLabel jFecha;
    private javax.swing.JLabel jFechaS;
    private javax.swing.JLabel jMarca;
    private javax.swing.JLabel jModelo;
    private javax.swing.JLabel jNombre;
    private javax.swing.JLabel jNumeroT;
    private javax.swing.JLabel jPlacaV;
    private javax.swing.JLabel jTelefono;
    private javax.swing.JLabel jTotal;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaE;
    private javax.swing.JTextField txtFechaS;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNUmeroTicket;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
